// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reshape.ElectricAi.LiveFeed.Persistence;

#nullable disable

namespace Reshape.ElectricAi.LiveFeed.Migrations
{
    [DbContext(typeof(FeedDbContext))]
    partial class FeedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("feed")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reshape.ElectricAi.LiveFeed.Entities.FeedEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGeneral")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PublishedUtc")
                        .IsDescending();

                    b.HasIndex("DeletedUtc", "PublishedUtc")
                        .HasFilter("\"DeletedUtc\" IS NULL");

                    b.ToTable("feed_entries", "feed");
                });

            modelBuilder.Entity("Reshape.ElectricAi.LiveFeed.Entities.FeedEntryArtist", b =>
                {
                    b.Property<Guid>("FeedEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArtistName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("FeedEntryId", "ArtistName");

                    b.ToTable("feed_entry_artists", "feed");
                });

            modelBuilder.Entity("Reshape.ElectricAi.LiveFeed.Entities.FeedEntryGenre", b =>
                {
                    b.Property<Guid>("FeedEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Genre")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("FeedEntryId", "Genre");

                    b.ToTable("feed_entry_genres", "feed");
                });

            modelBuilder.Entity("Reshape.ElectricAi.LiveFeed.Entities.FeedEntryArtist", b =>
                {
                    b.HasOne("Reshape.ElectricAi.LiveFeed.Entities.FeedEntry", "FeedEntry")
                        .WithMany("TargetArtists")
                        .HasForeignKey("FeedEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedEntry");
                });

            modelBuilder.Entity("Reshape.ElectricAi.LiveFeed.Entities.FeedEntryGenre", b =>
                {
                    b.HasOne("Reshape.ElectricAi.LiveFeed.Entities.FeedEntry", "FeedEntry")
                        .WithMany("TargetGenres")
                        .HasForeignKey("FeedEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedEntry");
                });

            modelBuilder.Entity("Reshape.ElectricAi.LiveFeed.Entities.FeedEntry", b =>
                {
                    b.Navigation("TargetArtists");

                    b.Navigation("TargetGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
