// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Reshape.ElectricAi.VectorDb.Persistence;

#nullable disable

namespace Reshape.ElectricAi.VectorDb.Migrations
{
    [DbContext(typeof(VectorDbContext))]
    partial class VectorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vector")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reshape.ElectricAi.VectorDb.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("CategoryTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<DateTimeOffset>("IngestedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryTags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CategoryTags"), "gin");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("QuestionId");

                    b.ToTable("answers", "vector");
                });

            modelBuilder.Entity("Reshape.ElectricAi.VectorDb.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IngestedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SourceHash")
                        .IsUnique();

                    b.ToTable("documents", "vector");
                });

            modelBuilder.Entity("Reshape.ElectricAi.VectorDb.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("CategoryTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryTags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CategoryTags"), "gin");

                    b.HasIndex("DocumentId");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("document_chunks", "vector");
                });

            modelBuilder.Entity("Reshape.ElectricAi.VectorDb.Entities.EventEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("CategoryTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<DateTimeOffset>("EventUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeedEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IngestedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TextRepresentation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryTags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CategoryTags"), "gin");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("FeedEntryId")
                        .IsUnique();

                    b.ToTable("event_entries", "vector");
                });

            modelBuilder.Entity("Reshape.ElectricAi.VectorDb.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("CategoryTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<DateTimeOffset>("IngestedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryTags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CategoryTags"), "gin");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("TextHash")
                        .IsUnique();

                    b.ToTable("questions", "vector");
                });

            modelBuilder.Entity("Reshape.ElectricAi.VectorDb.Entities.Answer", b =>
                {
                    b.HasOne("Reshape.ElectricAi.VectorDb.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Reshape.ElectricAi.VectorDb.Entities.DocumentChunk", b =>
                {
                    b.HasOne("Reshape.ElectricAi.VectorDb.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Reshape.ElectricAi.VectorDb.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Reshape.ElectricAi.VectorDb.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
