// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reshape.ElectricAi.Plans.Persistence;

#nullable disable

namespace Reshape.ElectricAi.Plans.Migrations
{
    [DbContext(typeof(PlansDbContext))]
    partial class PlansDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("plans")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Groups", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupPreferenceActivity", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("GroupId", "Activity");

                    b.ToTable("GroupPreferenceActivities", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupPreferenceArtist", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArtistName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("GroupId", "ArtistName");

                    b.ToTable("GroupPreferenceArtists", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupPreferenceFoodRestriction", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Restriction")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("GroupId", "Restriction");

                    b.ToTable("GroupPreferenceFoodRestrictions", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupPreferenceGenre", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Genre")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("GroupId", "Genre");

                    b.ToTable("GroupPreferenceGenres", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupPreferences", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Accommodation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AgeGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TicketType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Transport")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("GroupId");

                    b.ToTable("GroupPreferences", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ExportedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Plans", "plans", t =>
                        {
                            t.HasCheckConstraint("ck_plans_owner_xor_group", "(\"OwnerUserId\" IS NULL) <> (\"GroupId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PushSubscriptions", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByHash")
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .HasFilter("\"RevokedUtc\" IS NULL");

                    b.ToTable("RefreshTokens", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.UserPreferenceActivity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserId", "Activity");

                    b.ToTable("UserPreferenceActivities", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.UserPreferenceArtist", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArtistName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UserId", "ArtistName");

                    b.ToTable("UserPreferenceArtists", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.UserPreferenceFoodRestriction", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Restriction")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("UserId", "Restriction");

                    b.ToTable("UserPreferenceFoodRestrictions", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.UserPreferenceGenre", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Genre")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("UserId", "Genre");

                    b.ToTable("UserPreferenceGenres", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Accommodation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AgeGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TicketType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Transport")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences", "plans");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.Group", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupMember", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reshape.ElectricAi.Plans.Entities.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupPreferenceActivity", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.GroupPreferences", "GroupPreferences")
                        .WithMany("Activities")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupPreferences");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupPreferenceArtist", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.GroupPreferences", "GroupPreferences")
                        .WithMany("Artists")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupPreferences");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupPreferenceFoodRestriction", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.GroupPreferences", "GroupPreferences")
                        .WithMany("FoodRestrictions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupPreferences");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupPreferenceGenre", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.GroupPreferences", "GroupPreferences")
                        .WithMany("Genres")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupPreferences");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupPreferences", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.Group", "Group")
                        .WithOne("Preferences")
                        .HasForeignKey("Reshape.ElectricAi.Plans.Entities.GroupPreferences", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.Plan", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Reshape.ElectricAi.Plans.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Group");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.RefreshToken", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.UserPreferenceActivity", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.UserPreferences", "UserPreferences")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.UserPreferenceArtist", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.UserPreferences", "UserPreferences")
                        .WithMany("Artists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.UserPreferenceFoodRestriction", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.UserPreferences", "UserPreferences")
                        .WithMany("FoodRestrictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.UserPreferenceGenre", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.UserPreferences", "UserPreferences")
                        .WithMany("Genres")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.UserPreferences", b =>
                {
                    b.HasOne("Reshape.ElectricAi.Plans.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Reshape.ElectricAi.Plans.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.Group", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.GroupPreferences", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Artists");

                    b.Navigation("FoodRestrictions");

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.User", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("Preferences");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Reshape.ElectricAi.Plans.Entities.UserPreferences", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Artists");

                    b.Navigation("FoodRestrictions");

                    b.Navigation("Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
