/**
 * Static registry of Electric Castle artists. Keys are canonical identifiers;
 * values are display names as they appear on lineup materials. Keys are kept
 * 1-to-1 with `frontend/public/media/artists/<key>.jpg`.
 *
 * Adding an artist: add the entry here AND drop the matching `<key>.jpg` into
 * `frontend/public/media/artists/`.
 */
export const ARTISTS = {
    the_cure: 'THE CURE',
    twenty_one_pilots: 'TWENTY ONE PILOTS',
    teddy_swims: 'TEDDY SWIMS',
    chase_and_status: 'CHASE & STATUS',
    wet_leg: 'WET LEG',
    kneecap: 'KNEECAP',
    lp: 'LP',
    mochakk: 'MOCHAKK',
    nothing_but_thieves: 'NOTHING BUT THIEVES',
    wilkinson: 'WILKINSON',
    skream_and_benga: 'SKREAM & BENGA',
    subtronics: 'SUBTRONICS',
    yung_lean_and_bladee: 'YUNG LEAN & BLADEE',
    balu_brigada: 'BALU BRIGADA',
    sleaford_mods: 'SLEAFORD MODS',
    dogstar: 'DOGSTAR',
    sullivan_king: 'SULLIVAN KING',
    kölsch: 'KÖLSCH',
    deep_dish: 'DEEP DISH',
    nastia: 'NASTIA',
    maverick_sabre: 'MAVERICK SABRE',
    archive: 'ARCHIVE',
    jax_jones: 'JAX JONES',
    solardo: 'SOLARDO',
    house_of_protection: 'HOUSE OF PROTECTION',
    aaron_hibell: 'AARON HIBELL',
    mind_enterprises: 'MIND ENTERPRISES',
    kilimanjaro: 'KILIMANJARO',
    partiboi69: 'PARTIBOI69',
    sg_lewis: 'SG LEWIS',
    kasablanca: 'KASABLANCA',
    denis_sulta: 'DENIS SULTA',
    satori: 'SATORI',
    layla_benitez: 'LAYLA BENITEZ',
    anna: 'ANNA',
    oddisee_and_good_compny: 'ODDISEE & GOOD COMPNY',
    swimming_paul: 'SWIMMING PAUL',
    frost_children_dj_set: 'FROST CHILDREN (DJ SET)',
    irina_rimes: 'IRINA RIMES',
    the_motans: 'THE MOTANS',
    bosquito: 'BOSQUITO',
    viţa_de_vie: 'VIȚA DE VIE',
    taraphonics: 'TARAPHONICS',
    acid_pauli: 'ACID PAULI',
    deer_jade: 'DEER JADE',
    quantic_dj_set: 'QUANTIC (DJ SET)',
    gerd_janson: 'GERD JANSON',
    ogazón_b2b_ryan_elliott: 'OGAZÓN B2B RYAN ELLIOTT',
    egyptian_lover: 'EGYPTIAN LOVER',
    acid_arab_dj_set: 'ACID ARAB (DJ SET)',
    gia_fu: 'GIA FU',
    gojnea76: 'GOJNEA76',
    priku: 'PRIKU',
    just_mustard: 'JUST MUSTARD',
    pacifica: 'PACIFICA',
    dub_pistols: 'DUB PISTOLS',
    themba: 'THEMBA',
    kid_kapichi: 'KID KAPICHI',
    dj_marky: 'DJ MARKY',
    eliza_rose: 'ELIZA ROSE',
    indo_warehouse: 'INDO WAREHOUSE',
    congo_natty_ft_blackout_ja: 'CONGO NATTY FT. BLACKOUT JA',
    baron: 'BARON',
    pola_and_bryson: 'POLA & BRYSON',
    mechatok: 'MECHATOK',
    sainte_vie: 'SAINTE VIE',
    mc_gq: 'MC GQ',
    yĩn_yĩn: 'YĨN YĨN',
    trinix: 'TRINIX',
    lagartijeando: 'LAGARTIJEANDO',
    om_la_lună: 'OM LA LUNĂ',
    implant_pentru_refuz: 'IMPLANT PENTRU REFUZ',
    celelalte_cuvinte: 'CELELALTE CUVINTE',
    luna_amară: 'LUNA AMARĂ',
    hvnds: 'HVNDS',
    e_an_na: 'E-AN-NA',
    underwaves: 'UNDERWAVES',
    tania_turtureanu: 'TANIA TURTUREANU',
    ivan_and_the_parazol: 'IVAN & THE PARAZOL',
    ora_de_punk: 'ORA DE PUNK',
    da_te_n_sange_ora_de_punk: 'DA-TE-N SANGE (ORA DE PUNK)',
    martalogii_ora_de_punk: 'MARTALOGII (ORA DE PUNK)',
    parnaie_ora_de_punk: 'PARNAIE (ORA DE PUNK)',
    take_no_more_ora_de_punk: 'TAKE NO MORE (ORA DE PUNK)',
    mafalda: 'MAFALDA',
    rosa_pistola: 'ROSA PISTOLA',
    robin_and_the_backstabbers: 'ROBIN AND THE BACKSTABBERS',
    the_mono_jacks: 'THE MONO JACKS',
    byron: 'BYRON',
    level_up: 'LEVEL UP',
    souleance: 'SOULEANCE',
    sgt_pokes: 'SGT POKES',
    kitty_amor: 'KITTY AMOR',
    rosey_gold: 'ROSEY GOLD',
    soraya: 'SORAYA',
    skyla_tylaa: 'SKYLA TYLAA',
    ko_shin_moon: 'KO SHIN MOON',
    betty_bunny: 'BETTY BUNNY',
    eclair_fifi: 'ECLAIR FIFI',
    max_baby: 'MAX BABY',
    gans: 'GANS',
    koikoi: 'KOIKOI',
    honeyglaze: 'HONEYGLAZE',
    debdepan: 'DEBDEPAN',
    sunnan: 'SUNNAN',
    la_sécurité: 'LA SÉCURITÉ',
    armand_popa: 'ARMAND POPA',
    ana_coman: 'ANA COMAN',
    nidal: 'NIDAL',
    nuanţe: 'NUANȚE',
    anais_vacariu: 'ANAIS VACARIU',
    miau_wav: 'MIAU.WAV',
    romantic_jurgen: 'ROMANTIC JURGEN',
    funkorporation: 'FUNKORPORATION',
    c_c: '.C.C',
    akos: 'AKOS',
    aftermath: 'AFTERMATH',
    alee_who: 'ALEE WHO',
    ana_kalisee: 'ANA KALISEE',
    andreea_tupeu: 'ANDREEA TUPEU',
    andrei_puiu: 'ANDREI PUIU',
    artémis: 'ARTÉMIS',
    ashpot: 'ASHPOT',
    atmann_b2b_boda: 'ATMANN B2B BODA',
    audaks: 'AUDAKS',
    audio_state: 'AUDIO STATE',
    baba: 'BABA',
    bajzat: 'BAJZAT',
    bblove: 'BBLOVE',
    beatheice: 'BEATHEICE',
    blocksberg_and_memphys: 'BLOCKSBERG & MEMPHYS',
    boys_and_tears: 'BOYS AND TEARS',
    bully: 'BULLY',
    bross: 'BROSS',
    calibro_45: 'CALIBRO 45',
    cemi: 'CEMI',
    christian_thomson: 'CHRISTIAN THOMSON',
    corvin_and_buniku: 'CORVIN & BUNIKU',
    d_jhu: "D'JHU",
    dansen: 'DANSEN',
    dj_deny: 'DJ DENY',
    diana_sar: 'DIANA SAR',
    dodo: 'DODO',
    dubase: 'DUBASE',
    dwls: 'DWLS',
    efi: 'EFI',
    electric_brother: 'ELECTRIC BROTHER',
    elless: 'ELLESS',
    enăşescu: 'ENĂȘESCU',
    egonostas: 'EGONOSTAS',
    gabriel_m_b2b_tonia: 'GABRIEL M B2B TONIA',
    georgevlt: 'GEORGEVLT',
    giulee: 'GIULEE',
    heaven_can_wait: 'HEAVEN CAN WAIT',
    infragandhi: 'INFRAGANDHI',
    irina_mele: 'IRINA MELE',
    jay_bliss: 'JAY BLISS',
    jess_iszatt: 'JESS ISZATT',
    k_lu: 'K-LU',
    dj_keyser: 'DJ KEYSER',
    los_bastoneros: 'LOS BASTONEROS',
    loy: 'LOY',
    dj_mă_ta: 'DJ MĂ-TA',
    dj_magda: 'DJ MAGDA',
    mandu: 'MANDU',
    marwan_dua: 'MARWAN DUA',
    mathei: 'MATHEI',
    mihai_popoviciu: 'MIHAI POPOVICIU',
    mihu_hanging_around: 'MIHU (HANGING AROUND)',
    missile: 'MISSILE',
    mitsubitchi_b2b_mini_zucchini: 'MITSUBITCHI B2B MINI ZUCCHINI',
    miu: 'MIU',
    mr_goodalf: 'MR. GOODALF',
    muri: 'MURI',
    new_disorder: 'NEW DISORDER',
    nyss: 'NYSS',
    oktopus: 'OKTOPUS',
    olaf: 'OLAF',
    on_the_block: 'ON THE BLOCK',
    ozlemelk: 'OZLEMELK',
    paul_vlj: 'PAUL VLJ',
    pixar_stelar: 'PIXAR STELAR',
    popblock: 'POPBLOCK',
    radio_stefunk: 'RADIO STEFUNK',
    raoul: 'RAOUL',
    rapala: 'RAPALA',
    dj_sauce: 'DJ SAUCE',
    sixtee_seconds: 'SIXTEE SECONDS',
    socol: 'SOCOL',
    stf: 'STF',
    subliminal: 'SUBLIMINAL',
    sugar: 'SUGAR',
    trinkova: 'TRINKOVA',
    tripster: 'TRIPSTER',
    truthday_x_cristiana_dicianu: 'TRUTHDAY X CRISTIANA DICIANU',
    tudoran_ca_a_loco: 'TUDORAN (CA$$A LOCO)',
    dj_undoo: 'DJ UNDOO',
    utip: 'UTIP',
    dj_vasile: 'DJ VASILE',
    volt: 'VOLT',
    vygo: 'VYGO',
    zda: 'ZDA',
    zo: 'ZO',
} as const;

export type ArtistKey = keyof typeof ARTISTS;
export type ArtistName = (typeof ARTISTS)[ArtistKey];

export const ARTIST_KEYS = Object.keys(ARTISTS) as ArtistKey[];

export const PLACEHOLDER_ARTIST_IMAGE = '/media/artists/placeholder.jpg';

export const artistImagePath = (key: ArtistKey): string =>
    `/media/artists/${key}.jpg`;

/** Resolves any string (typically a BE-supplied artist key) to an image path. */
export function resolveArtistImage(key: string | null | undefined): string {
    return key && key in ARTISTS
        ? `/media/artists/${key}.jpg`
        : PLACEHOLDER_ARTIST_IMAGE;
}

/** Case-insensitive display-name → enum key reverse map. */
const KEY_BY_DISPLAY_NAME: ReadonlyMap<string, ArtistKey> = new Map(
    (Object.entries(ARTISTS) as Array<[ArtistKey, ArtistName]>).map(
        ([key, name]) => [name.toUpperCase(), key],
    ),
);

/** Find the enum key for a free-form display name (e.g. "The Cure", "THE CURE"). */
export function artistKeyForName(name: string | null | undefined): ArtistKey | null {
    if (!name) return null;
    return KEY_BY_DISPLAY_NAME.get(name.trim().toUpperCase()) ?? null;
}

/** Resolve an image path from a BE-supplied display name; placeholder on miss. */
export function resolveArtistImageByName(name: string | null | undefined): string {
    const key = artistKeyForName(name);
    return key ? artistImagePath(key) : PLACEHOLDER_ARTIST_IMAGE;
}
